### PR TITLE
Add vechai.info

### PR DESCRIPTION
**Pull request by NamPNQ**

### CODE REVIEW

**Comment by nhanb** [comment]
Some feedbacks:
- ca579e7: If we allow an empty `series_url` for a chapter, it will break the **Chapter list** button in chapter page. I think we should either remove this change or think of a better way to store the relationship between a series and a chapter.
- d1bbb5e:
  - You should add `series['authors']` or things will break.
  - Besides authors, please scrape the descriptions and tags too, don't cheat :P

The rest looks awesome. Thanks for the improvements! (y)

**Comment by nhanb** [comment]
Almost forgot:
- Please follow the PEP-8 code style standard. Specifically, any line must not have length > 79 (except for test files where the sample data strings are too long), comments should start with `#<space>`. Also please check and remove any repeated or unused import (`import re` is found twice in **vechai.py**). I use [flake8](http://flake8.readthedocs.org/en/latest/) to check these things automatically.
- a16301c: This file has no newline and the end of file. Please config your code editor to add newline at end of file. That's the standard UNIX text file convention, and if everyone follows this then our git diff won't be polluted by `no newline at end of file` messages when many people edit the same file.

Sorry for the nitpicks, if you don't want to do these style changes then I'll update them for you later before I merge. I should make official documentation and code style guidelines soon :)

**Comment by NamPNQ** [comment]
I don't use full pep8
I think you need re-design your database

**Comment by nhanb** [comment]
The database design is currently grossly denormalized, that's true. I originally wanted to try out [the App Engine / NoSQL way](http://bjk5.com/post/54202245691/the-app-engine-way), which basically means denormalizing everything and trying to make "read" operations fast. That has become a huge pain though... I'll spend this weekend working on some better design.

Thanks for the quick update! I'll review this a last time on the weekend. By the way, I prefer rebasing instead of merging directly (http://blog.spreedly.com/2014/06/24/merge-pull-request-considered-harmful/) :P

**Comment by nhanb** [comment]
Your changes have been merged with some improvements on top. Also deployed to pytaku-dev.appspot.com for some real-world use. If nothing goes wrong we'll deploy to pytaku's main page :+1:

**Pull request closed without merging**
